json.id item.id
json.name item.name
json.sport item.sport
json.price item.price
json.discounted item.discounted?
json.tax item.tax
json.total item.total
json.supplier_name item.supplier.name
json.images item.image_urls
json.message "HI!"